### ISSUE TITLE
Recommended way to log state

### ISSUE THREAD

**Issue by damassi** [dai-shi/react-hooks-easy-redux#7]
Noticed that when running `console.log(state)` it returns a proxy. What's the suggested way of logging out state? is it possible to unwrap the proxy that's returned from a `useReduxState` call?

**Comment by dai-shi** [comment]
Ah, good catch. Let me work on that.

**Comment by dai-shi** [comment]
@damassi 
It turns out that there's no easy way to console.log a proxy unwrapped.
What is the exact problem you are having?

This doesn't help, does it?
<img width="297" alt="image" src="https://user-images.githubusercontent.com/490574/54098101-63fc3680-43f6-11e9-9be4-cbd9649657f7.png">

You could try: `console.log(JSON.stringify(state))` which I don't recommend very much.
You could also use redux logging middleware.

**Comment by damassi** [comment]
Sounds good! was curious. Thanks for looking into it 👍
